"""
Phase 11.2 — Comprehensive IPL Player Registry

Maps all 805 Cricsheet shortcode names found in the DB to their
full canonical names. Built from the complete player list exported
from player_batting_stats and player_bowling_stats tables.

Format: "DB shortcode": "Full canonical name"

Resolution approach:
- Cricsheet format is Initial(s) + Surname e.g. "JJ Bumrah" = Jasprit Bumrah
- Well-known players resolved from cricket knowledge
- Players with unique surnames resolved from initials
- Ambiguous cases kept as-is (e.g. "A Singh" has many possible players)
"""

PLAYER_REGISTRY = {

    # ── A ──────────────────────────────────────────────────────────────────
    "A Ashish Reddy":    "A Ashish Reddy",
    "A Badoni":          "Ayush Badoni",
    "A Chandila":        "Ankit Chandila",
    "A Chopra":          "Aakash Chopra",
    "A Choudhary":       "A Choudhary",
    "A Dananjaya":       "Akila Dananjaya",
    "A Flintoff":        "Andrew Flintoff",
    "A Kamboj":          "Anshul Kamboj",
    "A Kumble":          "Anil Kumble",
    "A Manohar":         "A Manohar",
    "A Mhatre":          "A Mhatre",
    "A Mishra":          "Amit Mishra",
    "A Mithun":          "A Mithun",
    "A Mukund":          "Abhinav Mukund",
    "A Nehra":           "Ashish Nehra",
    "A Nel":             "Andre Nel",
    "A Nortje":          "Anrich Nortje",
    "A Raghuvanshi":     "A Raghuvanshi",
    "A Singh":           "A Singh",
    "A Symonds":         "Andrew Symonds",
    "A Tomar":           "A Tomar",
    "A Uniyal":          "A Uniyal",
    "A Zampa":           "Adam Zampa",
    "AA Bilakhia":       "AA Bilakhia",
    "AA Chavan":         "Ankeet Chavan",
    "AA Jhunjhunwala":   "AA Jhunjhunwala",
    "AA Kazi":           "AA Kazi",
    "AA Kulkarni":       "AA Kulkarni",
    "AA Noffke":         "Ashley Noffke",
    "AB Agarkar":        "Ajit Agarkar",
    "AB Barath":         "Adrian Barath",
    "AB Dinda":          "Ashok Dinda",
    "AB McDonald":       "Andrew McDonald",
    "AB de Villiers":    "AB de Villiers",
    "AC Blizzard":       "AC Blizzard",
    "AC Gilchrist":      "Adam Gilchrist",
    "AC Thomas":         "Alfonso Thomas",
    "AC Voges":          "Adam Voges",
    "AD Hales":          "Alex Hales",
    "AD Mascarenhas":    "Dimitri Mascarenhas",
    "AD Mathews":        "Angelo Mathews",
    "AD Nath":           "AD Nath",
    "AD Russell":        "Andre Russell",
    "AF Milne":          "Adam Milne",
    "AG Murtaza":        "AG Murtaza",
    "AG Paunikar":       "AG Paunikar",
    "AJ Finch":          "Aaron Finch",
    "AJ Hosein":         "Akeal Hosein",
    "AJ Turner":         "AJ Turner",
    "AJ Tye":            "Andrew Tye",
    "AK Markram":        "Aiden Markram",
    "AL Menaria":        "AL Menaria",
    "AM Ghazanfar":      "AM Ghazanfar",
    "AM Nayar":          "Abhishek Nayar",
    "AM Rahane":         "Ajinkya Rahane",
    "AM Salvi":          "Abhijit Salvi",
    "AN Ahmed":          "AN Ahmed",
    "AN Ghosh":          "AN Ghosh",
    "AP Dole":           "AP Dole",
    "AP Majumdar":       "AP Majumdar",
    "AP Tare":           "Aditya Tare",
    "AR Bawne":          "AR Bawne",
    "AR Patel":          "Axar Patel",
    "AS Joseph":         "Alzarri Joseph",
    "AS Rajpoot":        "AS Rajpoot",
    "AS Raut":           "AS Raut",
    "AS Roy":            "Ambati Rayudu",
    "AS Yadav":          "AS Yadav",
    "AT Carey":          "Alex Carey",
    "AT Rayudu":         "Ambati Rayudu",
    "AU Rashid":         "Adil Rashid",
    "AUK Pathan":        "Irfan Pathan",
    "Abdul Basith":      "Abdul Basith",
    "Abdul Samad":       "Abdul Samad",
    "Abdur Razzak":      "Abdur Razzak",
    "Abhinandan Singh":  "Abhinandan Singh",
    "Abhishek Sharma":   "Abhishek Sharma",
    "Abishek Porel":     "Abishek Porel",
    "Akash Deep":        "Akash Deep",
    "Akash Madhwal":     "Akash Madhwal",
    "Akash Singh":       "Akash Singh",
    "Akshat Raghuwanshi": "Akshat Raghuwanshi",
    "Aman Hakim Khan":   "Aman Hakim Khan",
    "Anand Rajan":       "Anand Rajan",
    "Aniket Verma":      "Aniket Verma",
    "Anirudh Singh":     "Anirudh Singh",
    "Ankit Sharma":      "Ankit Sharma",
    "Ankit Soni":        "Ankit Soni",
    "Anmolpreet Singh":  "Anmolpreet Singh",
    "Anuj Rawat":        "Anuj Rawat",
    "Anureet Singh":     "Anureet Singh",
    "Arjun Tendulkar":   "Arjun Tendulkar",
    "Arshad Khan":       "Arshad Khan",
    "Arshad Khan (2)":   "Arshad Khan",
    "Arshdeep Singh":    "Arshdeep Singh",
    "Ashok Sharma":      "Ashok Sharma",
    "Ashutosh Sharma":   "Ashutosh Sharma",
    "Ashwani Kumar":     "Ashwani Kumar",
    "Atharva Taide":     "Atharva Taide",
    "Auqib Nabi":        "Auqib Nabi",
    "Avesh Khan":        "Avesh Khan",
    "Azhar Mahmood":     "Azhar Mahmood",
    "Azmatullah Omarzai": "Azmatullah Omarzai",

    # ── B ──────────────────────────────────────────────────────────────────
    "B Akhil":           "B Akhil",
    "B Chipli":          "B Chipli",
    "B Geeves":          "Brett Geeves",
    "B Indrajith":       "B Indrajith",
    "B Kumar":           "Bhuvneshwar Kumar",
    "B Laughlin":        "Ben Laughlin",
    "B Lee":             "Brett Lee",
    "B Muzarabani":      "Blessing Muzarabani",
    "B Sai Sudharsan":   "B Sai Sudharsan",
    "B Stanlake":        "Billy Stanlake",
    "B Sumanth":         "B Sumanth",
    "BA Bhatt":          "BA Bhatt",
    "BA Stokes":         "Ben Stokes",
    "BAW Mendis":        "Ajantha Mendis",
    "BB McCullum":       "Brendon McCullum",
    "BB Samantray":      "BB Samantray",
    "BB Sran":           "Barinder Sran",
    "BCJ Cutting":       "Ben Cutting",
    "BE Hendricks":      "Beuran Hendricks",
    "BJ Dwarshuis":      "BJ Dwarshuis",
    "BJ Haddin":         "Brad Haddin",
    "BJ Hodge":          "Brad Hodge",
    "BJ Rohrer":         "BJ Rohrer",
    "BKG Mendis":        "Kusal Mendis",
    "BMAJ Mendis":       "BMAJ Mendis",
    "BR Dunk":           "BR Dunk",
    "BR Sharath":        "BR Sharath",
    "BW Hilfenhaus":     "Ben Hilfenhaus",
    "Basil Thampi":      "Basil Thampi",
    "Bipul Sharma":      "Bipul Sharma",
    "Brijesh Sharma":    "Brijesh Sharma",

    # ── C ──────────────────────────────────────────────────────────────────
    "C Bosch":           "C Bosch",
    "C Connolly":        "C Connolly",
    "C Ganapathy":       "C Ganapathy",
    "C Green":           "Cameron Green",
    "C Madan":           "C Madan",
    "C Munro":           "Colin Munro",
    "C Nanda":           "C Nanda",
    "C Sakariya":        "Chetan Sakariya",
    "C de Grandhomme":   "Colin de Grandhomme",
    "CA Ingram":         "Colin Ingram",
    "CA Lynn":           "Chris Lynn",
    "CA Pujara":         "Cheteshwar Pujara",
    "CH Gayle":          "Chris Gayle",
    "CH Morris":         "Chris Morris",
    "CJ Anderson":       "Corey Anderson",
    "CJ Dala":           "CJ Dala",
    "CJ Ferguson":       "CJ Ferguson",
    "CJ Green":          "CJ Green",
    "CJ Jordan":         "Chris Jordan",
    "CJ McKay":          "Clint McKay",
    "CK Kapugedera":     "Chamara Kapugedera",
    "CK Langeveldt":     "Charl Langeveldt",
    "CL White":          "Cameron White",
    "CM Gautam":         "CM Gautam",
    "CR Brathwaite":     "Carlos Brathwaite",
    "CR Woakes":         "Chris Woakes",
    "CRD Fernando":      "Dilhara Fernando",
    "CV Varun":          "CV Varun",

    # ── D ──────────────────────────────────────────────────────────────────
    "D Brevis":          "Dewald Brevis",
    "D Ferreira":        "D Ferreira",
    "D Jansen":          "Duanne Jansen",
    "D Kalyankrishna":   "D Kalyankrishna",
    "D Madushanka":      "Dilshan Madushanka",
    "D Padikkal":        "Devdutt Padikkal",
    "D Pretorius":       "Dwaine Pretorius",
    "D Salunkhe":        "D Salunkhe",
    "D Wiese":           "David Wiese",
    "D du Preez":        "D du Preez",
    "DA Miller":         "David Miller",
    "DA Payne":          "DA Payne",
    "DA Warner":         "David Warner",
    "DAJ Bracewell":     "DAJ Bracewell",
    "DB Das":            "DB Das",
    "DB Ravi Teja":      "DB Ravi Teja",
    "DE Bollinger":      "Doug Bollinger",
    "DG Nalkande":       "DG Nalkande",
    "DH Yagnik":         "DH Yagnik",
    "DJ Bravo":          "Dwayne Bravo",
    "DJ Harris":         "Ryan Harris",
    "DJ Hooda":          "Deepak Hooda",
    "DJ Hussey":         "David Hussey",
    "DJ Jacobs":         "DJ Jacobs",
    "DJ Malan":          "Dawid Malan",
    "DJ Mitchell":       "Daryl Mitchell",
    "DJ Muthuswami":     "DJ Muthuswami",
    "DJ Thornely":       "DJ Thornely",
    "DJ Willey":         "David Willey",
    "DJG Sammy":         "Darren Sammy",
    "DJM Short":         "DJM Short",
    "DL Chahar":         "Deepak Chahar",
    "DL Vettori":        "Daniel Vettori",
    "DM Bravo":          "Dwayne Bravo",
    "DNT Zoysa":         "Nuwan Zoysa",
    "DP Conway":         "Devon Conway",
    "DP Nannes":         "Dirk Nannes",
    "DP Vijaykumar":     "DP Vijaykumar",
    "DPMD Jayawardene":  "Mahela Jayawardene",
    "DR Martyn":         "Damien Martyn",
    "DR Sams":           "Daniel Sams",
    "DR Shorey":         "DR Shorey",
    "DR Smith":          "DR Smith",
    "DS Kulkarni":       "Dhawal Kulkarni",
    "DS Lehmann":        "Darren Lehmann",
    "DS Rathi":          "DS Rathi",
    "DT Christian":      "Dan Christian",
    "DT Patil":          "DT Patil",
    "DV Malewar":        "DV Malewar",
    "DW Steyn":          "Dale Steyn",
    "Dhruv Jurel":       "Dhruv Jurel",

    # ── E ──────────────────────────────────────────────────────────────────
    "E Lewis":           "Evin Lewis",
    "E Malinga":         "E Malinga",
    "EJG Morgan":        "Eoin Morgan",
    "ER Dwivedi":        "ER Dwivedi",

    # ── F ──────────────────────────────────────────────────────────────────
    "F Behardien":       "Farhaan Behardien",
    "F du Plessis":      "Faf du Plessis",
    "FA Allen":          "Fabian Allen",
    "FH Allen":          "FH Allen",
    "FH Edwards":        "Fidel Edwards",
    "FY Fazal":          "FY Fazal",
    "Fazalhaq Farooqi":  "Fazalhaq Farooqi",

    # ── G ──────────────────────────────────────────────────────────────────
    "G Coetzee":         "Gerald Coetzee",
    "G Gambhir":         "Gautam Gambhir",
    "GB Hogg":           "Brad Hogg",
    "GC Smith":          "Graeme Smith",
    "GC Viljoen":        "GC Viljoen",
    "GD McGrath":        "Glenn McGrath",
    "GD Phillips":       "Glenn Phillips",
    "GF Linde":          "George Linde",
    "GH Vihari":         "Hanuma Vihari",
    "GHS Garton":        "GHS Garton",
    "GJ Bailey":         "George Bailey",
    "GJ Maxwell":        "Glenn Maxwell",
    "GR Napier":         "Graham Napier",
    "GS Sandhu":         "Gurkeerat Singh",
    "Gagandeep Singh":   "Gagandeep Singh",
    "Gulbadin Naib":     "Gulbadin Naib",
    "Gurjapneet Singh":  "Gurjapneet Singh",
    "Gurkeerat Singh":   "Gurkeerat Singh",
    "Gurnoor Brar":      "Gurnoor Brar",

    # ── H ──────────────────────────────────────────────────────────────────
    "H Das":             "H Das",
    "H Klaasen":         "Heinrich Klaasen",
    "H Sharma":          "Himanshu Sharma",
    "HC Brook":          "Harry Brook",
    "HE van der Dussen": "Rassie van der Dussen",
    "HF Gurney":         "Harry Gurney",
    "HH Gibbs":          "Herschelle Gibbs",
    "HH Pandya":         "Hardik Pandya",
    "HM Amla":           "Hashim Amla",
    "HR Shokeen":        "Harpreet Brar",
    "HV Patel":          "Harshal Patel",
    "Harbhajan Singh":   "Harbhajan Singh",
    "Harmeet Singh":     "Harmeet Singh",
    "Harpreet Brar":     "Harpreet Brar",
    "Harpreet Singh":    "Harpreet Singh",
    "Harsh Dubey":       "Harsh Dubey",
    "Harshit Rana":      "Harshit Rana",
    "Himmat Singh":      "Himmat Singh",

    # ── I ──────────────────────────────────────────────────────────────────
    "I Malhotra":        "I Malhotra",
    "I Sharma":          "Ishant Sharma",
    "I Udana":           "Isuru Udana",
    "IC Pandey":         "IC Pandey",
    "IC Porel":          "Ishan Porel",
    "IK Pathan":         "Irfan Pathan",
    "IR Jaggi":          "IR Jaggi",
    "IS Sodhi":          "Ish Sodhi",
    "Imran Tahir":       "Imran Tahir",
    "Iqbal Abdulla":     "Iqbal Abdulla",
    "Ishan Kishan":      "Ishan Kishan",

    # ── J ──────────────────────────────────────────────────────────────────
    "J Arunkumar":       "J Arunkumar",
    "J Botha":           "Johan Botha",
    "J Fraser-McGurk":   "Jake Fraser-McGurk",
    "J Little":          "J Little",
    "J Overton":         "J Overton",
    "J Suchith":         "J Suchith",
    "J Syed Mohammad":   "J Syed Mohammad",
    "J Theron":          "J Theron",
    "J Yadav":           "J Yadav",
    "JA Duffy":          "JA Duffy",
    "JA Morkel":         "Albie Morkel",
    "JA Richardson":     "JA Richardson",
    "JC Archer":         "Jofra Archer",
    "JC Buttler":        "Jos Buttler",
    "JD Ryder":          "Jesse Ryder",
    "JD Unadkat":        "Jaydev Unadkat",
    "JDP Oram":          "Jacob Oram",
    "JDS Neesham":       "Jimmy Neesham",
    "JE Root":           "Joe Root",
    "JE Taylor":         "Jerome Taylor",
    "JEC Franklin":      "James Franklin",
    "JG Bethell":        "JG Bethell",
    "JH Kallis":         "Jacques Kallis",
    "JJ Bumrah":         "Jasprit Bumrah",
    "JJ Roy":            "Jason Roy",
    "JJ van der Wath":   "JJ van der Wath",
    "JL Denly":          "Joe Denly",
    "JL Pattinson":      "James Pattinson",
    "JM Bairstow":       "Jonny Bairstow",
    "JM Kemp":           "Justin Kemp",
    "JM Sharma":         "JM Sharma",
    "JO Holder":         "Jason Holder",
    "JP Behrendorff":    "Jason Behrendorff",
    "JP Duminy":         "JP Duminy",
    "JP Faulkner":       "James Faulkner",
    "JP Inglis":         "Josh Inglis",
    "JPR Scantlebury-Searles": "JPR Scantlebury-Searles",
    "JR Hazlewood":      "Josh Hazlewood",
    "JR Hopes":          "James Hopes",
    "JR Philippe":       "Josh Philippe",
    "JW Hastings":       "John Hastings",
    "Jalaj S Saxena":    "Jalaj Saxena",
    "Jaskaran Singh":    "Jaskaran Singh",
    "Joginder Sharma":   "Joginder Sharma",

    # ── K ──────────────────────────────────────────────────────────────────
    "K Goel":            "K Goel",
    "K Gowtham":         "Krishnappa Gowtham",
    "K Kartikeya":       "K Kartikeya",
    "K Khejroliya":      "K Khejroliya",
    "K Rabada":          "Kagiso Rabada",
    "K Santokie":        "Krishmar Santokie",
    "K Upadhyay":        "K Upadhyay",
    "K Yadav":           "Kuldeep Yadav",
    "KA Jamieson":       "Kyle Jamieson",
    "KA Maharaj":        "Keshav Maharaj",
    "KA Pollard":        "Kieron Pollard",
    "KAJ Roach":         "Kemar Roach",
    "KB Arun Karthik":   "KB Arun Karthik",
    "KC Cariappa":       "KC Cariappa",
    "KC Sangakkara":     "Kumar Sangakkara",
    "KD Karthik":        "Dinesh Karthik",
    "KH Pandya":         "Krunal Pandya",
    "KJ Abbott":         "Kyle Abbott",
    "KK Ahmed":          "KK Ahmed",
    "KK Cooper":         "KK Cooper",
    "KK Nair":           "Karun Nair",
    "KL Nagarkoti":      "KL Nagarkoti",
    "KL Rahul":          "KL Rahul",
    "KM Asif":           "KM Asif",
    "KM Jadhav":         "Kedar Jadhav",
    "KMA Paul":          "KMA Paul",
    "KMDN Kulasekara":   "Nuwan Kulasekara",
    "KP Appanna":        "KP Appanna",
    "KP Pietersen":      "Kevin Pietersen",
    "KR Mayers":         "Kyle Mayers",
    "KR Sen":            "KR Sen",
    "KS Bharat":         "KS Bharat",
    "KS Rathore":        "KS Rathore",
    "KS Sharma":         "KS Sharma",
    "KS Williamson":     "Kane Williamson",
    "KT Maphaka":        "KT Maphaka",
    "KV Sharma":         "KV Sharma",
    "KW Richardson":     "KW Richardson",
    "Kamran Akmal":      "Kamran Akmal",
    "Kamran Khan":       "Kamran Khan",
    "Karanveer Singh":   "Karanveer Singh",
    "Karim Janat":       "Karim Janat",
    "Kartik Sharma":     "Kartik Sharma",
    "Kartik Tyagi":      "Kartik Tyagi",
    "Krish Bhagat":      "Krish Bhagat",
    "Kuldeep Yadav":     "Kuldeep Yadav",
    "Kumar Kushagra":    "Kumar Kushagra",

    # ── L ──────────────────────────────────────────────────────────────────
    "L Ablish":          "L Ablish",
    "L Balaji":          "Lakshmipathy Balaji",
    "L Ngidi":           "Lungi Ngidi",
    "L Ronchi":          "Luke Ronchi",
    "L Wood":            "Luke Wood",
    "LA Carseldine":     "LA Carseldine",
    "LA Pomersbach":     "Luke Pomersbach",
    "LB Williams":       "LB Williams",
    "LE Plunkett":       "Liam Plunkett",
    "LG Pretorius":      "LG Pretorius",
    "LH Ferguson":       "Lockie Ferguson",
    "LI Meriwala":       "LI Meriwala",
    "LJ Wright":         "Luke Wright",
    "LMP Simmons":       "Lendl Simmons",
    "LPC Silva":         "LPC Silva",
    "LR Shukla":         "Laxmi Ratan Shukla",
    "LRPL Taylor":       "Ross Taylor",
    "LS Livingstone":    "Liam Livingstone",
    "Lalit Yadav":       "Lalit Yadav",
    "Liton Das":         "Liton Das",

    # ── M ──────────────────────────────────────────────────────────────────
    "M Ashwin":          "Murugan Ashwin",
    "M Jansen":          "Marco Jansen",
    "M Kaif":            "Mohammad Kaif",
    "M Kartik":          "Murali Kartik",
    "M Klinger":         "Michael Klinger",
    "M Manhas":          "Mithun Manhas",
    "M Markande":        "Mayank Markande",
    "M Morkel":          "Morne Morkel",
    "M Muralitharan":    "Muttiah Muralitharan",
    "M Ntini":           "Makhaya Ntini",
    "M Pathirana":       "Matheesha Pathirana",
    "M Prasidh Krishna": "Prasidh Krishna",
    "M Rawat":           "M Rawat",
    "M Shahrukh Khan":   "M Shahrukh Khan",
    "M Siddharth":       "M Siddharth",
    "M Theekshana":      "Maheesh Theekshana",
    "M Tiwari":          "Manoj Tiwary",
    "M Vijay":           "Murali Vijay",
    "M Vohra":           "Manan Vohra",
    "M de Lange":        "Marchant de Lange",
    "MA Agarwal":        "Mayank Agarwal",
    "MA Khote":          "MA Khote",
    "MA Starc":          "Mitchell Starc",
    "MA Wood":           "Mark Wood",
    "MB Parmar":         "MB Parmar",
    "MC Henriques":      "Moises Henriques",
    "MC Juneja":         "MC Juneja",
    "MD Choudhary":      "Mukesh Choudhary",
    "MD Mishra":         "Deepak Mishra",
    "MD Shanaka":        "Dasun Shanaka",
    "MDKJ Perera":       "Kusal Perera",
    "MEK Hussey":        "Mike Hussey",
    "MF Maharoof":       "Farveez Maharoof",
    "MG Bracewell":      "Michael Bracewell",
    "MG Johnson":        "Mitchell Johnson",
    "MG Neser":          "Michael Neser",
    "MJ Clarke":         "Michael Clarke",
    "MJ Guptill":        "Martin Guptill",
    "MJ Henry":          "Matt Henry",
    "MJ Lumb":           "Michael Lumb",
    "MJ McClenaghan":    "Mitchell McClenaghan",
    "MJ Owen":           "MJ Owen",
    "MJ Santner":        "Mitchell Santner",
    "MJ Suthar":         "MJ Suthar",
    "MK Lomror":         "Mahipal Lomror",
    "MK Pandey":         "Manish Pandey",
    "MK Tiwary":         "Manoj Tiwary",
    "ML Hayden":         "Matthew Hayden",
    "MM Ali":            "Moeen Ali",
    "MM Patel":          "Munaf Patel",
    "MM Sharma":         "MM Sharma",
    "MN Samuels":        "Marlon Samuels",
    "MN van Wyk":        "MN van Wyk",
    "MP Breetzke":       "MP Breetzke",
    "MP Stoinis":        "Marcus Stoinis",
    "MP Yadav":          "Mayank Yadav",
    "MR Marsh":          "Mitchell Marsh",
    "MS Bhandage":       "MS Bhandage",
    "MS Bisla":          "Manvinder Bisla",
    "MS Dhoni":          "Mahendra Singh Dhoni",
    "MS Gony":           "Manpreet Gony",
    "MS Wade":           "Matthew Wade",
    "MV Boucher":        "Mark Boucher",
    "MW Short":          "MW Short",
    "Mandeep Singh":     "Mandeep Singh",
    "Mashrafe Mortaza":  "Mashrafe Mortaza",
    "Mayank Dagar":      "Mayank Dagar",
    "Misbah-ul-Haq":     "Misbah-ul-Haq",
    "Mohammad Ashraful": "Mohammad Ashraful",
    "Mohammad Asif":     "Mohammad Asif",
    "Mohammad Hafeez":   "Mohammad Hafeez",
    "Mohammad Nabi":     "Mohammad Nabi",
    "Mohammed Shami":    "Mohammed Shami",
    "Mohammed Siraj":    "Mohammed Siraj",
    "Mohit Rathee":      "Mohit Rathee",
    "Mohsin Khan":       "Mohsin Khan",
    "Monu Kumar":        "Monu Kumar",
    "Mujeeb Ur Rahman":  "Mujeeb Ur Rahman",
    "Mukesh Choudhary":  "Mukesh Choudhary",
    "Mukesh Kumar":      "Mukesh Kumar",
    "Musheer Khan":      "Musheer Khan",
    "Mustafizur Rahman": "Mustafizur Rahman",

    # ── N ──────────────────────────────────────────────────────────────────
    "N Burger":          "N Burger",
    "N Jagadeesan":      "N Jagadeesan",
    "N Pooran":          "Nicholas Pooran",
    "N Rana":            "Nitish Rana",
    "N Saini":           "Navdeep Saini",
    "N Sindhu":          "N Sindhu",
    "N Thushara":        "N Thushara",
    "N Wadhera":         "N Wadhera",
    "NA Saini":          "Navdeep Saini",
    "NB Singh":          "NB Singh",
    "ND Doshi":          "Nayan Doshi",
    "NJ Maddinson":      "Nic Maddinson",
    "NJ Rimmington":     "NJ Rimmington",
    "NK Patel":          "NK Patel",
    "NL McCullum":       "Nathan McCullum",
    "NLTC Perera":       "Thisara Perera",
    "NM Coulter-Nile":   "Nathan Coulter-Nile",
    "NS Naik":           "NS Naik",
    "NT Ellis":          "Nathan Ellis",
    "NV Ojha":           "Naman Ojha",
    "Naman Dhir":        "Naman Dhir",
    "Navdeep Saini":     "Navdeep Saini",
    "Naveen-ul-Haq":     "Naveen-ul-Haq",
    "Nithish Kumar Reddy": "Nitish Kumar Reddy",
    "Noor Ahmad":        "Noor Ahmad",

    # ── O ──────────────────────────────────────────────────────────────────
    "O Thomas":          "Oshane Thomas",
    "OA Shah":           "Owais Shah",
    "OC McCoy":          "Obed McCoy",
    "OF Smith":          "Dwayne Smith",

    # ── P ──────────────────────────────────────────────────────────────────
    "P Amarnath":        "P Amarnath",
    "P Awana":           "Parvinder Awana",
    "P Chopra":          "P Chopra",
    "P Dogra":           "P Dogra",
    "P Dubey":           "Prashant Dubey",
    "P Kumar":           "Praveen Kumar",
    "P Negi":            "Pawan Negi",
    "P Nissanka":        "Pathum Nissanka",
    "P Parameswaran":    "P Parameswaran",
    "P Prasanth":        "P Prasanth",
    "P Ray Barman":      "P Ray Barman",
    "P Sahu":            "P Sahu",
    "P Simran Singh":    "P Simran Singh",
    "P Suyal":           "P Suyal",
    "PA Patel":          "Parthiv Patel",
    "PA Reddy":          "PA Reddy",
    "PBB Rajapaksa":     "Bhanuka Rajapaksa",
    "PC Valthaty":       "Paul Valthaty",
    "PD Collingwood":    "Paul Collingwood",
    "PD Salt":           "Phil Salt",
    "PH Solanki":        "PH Solanki",
    "PHKD Mendis":       "PHKD Mendis",
    "PJ Cummins":        "Pat Cummins",
    "PJ Sangwan":        "Pradeep Sangwan",
    "PK Garg":           "PK Garg",
    "PM Sarvesh Kumar":  "PM Sarvesh Kumar",
    "PN Mankad":         "PN Mankad",
    "PP Chawla":         "Piyush Chawla",
    "PP Hinge":          "PP Hinge",
    "PP Ojha":           "Pragyan Ojha",
    "PP Shaw":           "Prithvi Shaw",
    "PR Shah":           "PR Shah",
    "PR Veer":           "PR Veer",
    "PSP Handscomb":     "Peter Handscomb",
    "PV Tambe":          "Pravin Tambe",
    "PVD Chameera":      "Dushmantha Chameera",
    "PVSN Raju":         "PVSN Raju",
    "PWA Mulder":        "Wiaan Mulder",
    "PWH de Silva":      "Wanindu Hasaranga",
    "Pankaj Singh":      "Pankaj Singh",
    "Parvez Rasool":     "Parvez Rasool",
    "Prince Yadav":      "Prince Yadav",
    "Priyansh Arya":     "Priyansh Arya",

    # ── Q ──────────────────────────────────────────────────────────────────
    "Q de Kock":         "Quinton de Kock",

    # ── R ──────────────────────────────────────────────────────────────────
    "R Ashwin":          "Ravichandran Ashwin",
    "R Bhatia":          "Rajat Bhatia",
    "R Bishnoi":         "Ravi Bishnoi",
    "R Dhawan":          "R Dhawan",
    "R Dravid":          "Rahul Dravid",
    "R Goyal":           "Rahul Goyal",
    "R McLaren":         "Ryan McLaren",
    "R Minz":            "R Minz",
    "R Ninan":           "R Ninan",
    "R Parag":           "Riyan Parag",
    "R Powell":          "Rovman Powell",
    "R Rampaul":         "Ravi Rampaul",
    "R Ravindra":        "Rachin Ravindra",
    "R Sai Kishore":     "R Sai Kishore",
    "R Sanjay Yadav":    "R Sanjay Yadav",
    "R Sathish":         "R Sathish",
    "R Sharma":          "Rohit Sharma",
    "R Shepherd":        "Romario Shepherd",
    "R Shukla":          "Rahul Shukla",
    "R Smaran":          "R Smaran",
    "R Tewatia":         "Rahul Tewatia",
    "R Vinay Kumar":     "Vinay Kumar",
    "RA Bawa":           "RA Bawa",
    "RA Jadeja":         "Ravindra Jadeja",
    "RA Shaikh":         "RA Shaikh",
    "RA Tripathi":       "Rahul Tripathi",
    "RD Chahar":         "Rahul Chahar",
    "RD Gaikwad":        "Ruturaj Gaikwad",
    "RD Rickelton":      "Ryan Rickelton",
    "RE Levi":           "Richard Levi",
    "RE van der Merwe":  "Roelof van der Merwe",
    "RG More":           "RG More",
    "RG Sharma":         "Rohit Sharma",
    "RJ Gleeson":        "Richard Gleeson",
    "RJ Harris":         "Ryan Harris",
    "RJ Peterson":       "Robin Peterson",
    "RJ Quiney":         "RJ Quiney",
    "RJW Topley":        "Reece Topley",
    "RK Bhui":           "RK Bhui",
    "RK Singh":          "RP Singh",
    "RM Patidar":        "Rajat Patidar",
    "RN ten Doeschate":  "Ryan ten Doeschate",
    "RP Meredith":       "Riley Meredith",
    "RP Singh":          "RP Singh",
    "RR Bhatkal":        "RR Bhatkal",
    "RR Bose":           "RR Bose",
    "RR Pant":           "Rishabh Pant",
    "RR Powar":          "Ramesh Powar",
    "RR Raje":           "RR Raje",
    "RR Rossouw":        "Rilee Rossouw",
    "RR Sarwan":         "Ramnaresh Sarwan",
    "RS Bopara":         "Ravi Bopara",
    "RS Gavaskar":       "RS Gavaskar",
    "RS Ghosh":          "RS Ghosh",
    "RS Hangargekar":    "RS Hangargekar",
    "RS Sodhi":          "RS Sodhi",
    "RT Ponting":        "Ricky Ponting",
    "RV Gomez":          "RV Gomez",
    "RV Patel":          "RV Patel",
    "RV Uthappa":        "Robin Uthappa",
    "RW Price":          "RW Price",
    "Raghu Sharma":      "Raghu Sharma",
    "Rahmanullah Gurbaz": "Rahmanullah Gurbaz",
    "Ramandeep Singh":   "Ramandeep Singh",
    "Rashid Khan":       "Rashid Khan",
    "Rasikh Salam":      "Rasikh Salam",
    "Ravi Bishnoi":      "Ravi Bishnoi",
    "Ravi Singh":        "Ravi Singh",

    # ── S ──────────────────────────────────────────────────────────────────
    "S Anirudha":        "S Anirudha",
    "S Aravind":         "S Aravind",
    "S Arora":           "S Arora",
    "S Badree":          "Samuel Badree",
    "S Badrinath":       "Subramaniam Badrinath",
    "S Chanderpaul":     "Shivnarine Chanderpaul",
    "S Dhawan":          "Shikhar Dhawan",
    "S Dube":            "Shivam Dube",
    "S Gopal":           "Shreyas Gopal",
    "S Joseph":          "S Joseph",
    "S Kaul":            "Siddarth Kaul",
    "S Kaushik":         "S Kaushik",
    "S Ladda":           "S Ladda",
    "S Lamichhane":      "Sandeep Lamichhane",
    "S Midhun":          "S Midhun",
    "S Nadeem":          "Shahbaz Nadeem",
    "S Narwal":          "S Narwal",
    "S Rana":            "Shubman Gill",
    "S Randiv":          "Suraj Randiv",
    "S Sandeep Warrier": "Sandeep Warrier",
    "S Sohal":           "S Sohal",
    "S Sreesanth":       "S Sreesanth",
    "S Sriram":          "S Sriram",
    "S Tyagi":           "Siddharth Tyagi",
    "S Vidyut":          "S Vidyut",
    "SA Abbott":         "Sean Abbott",
    "SA Asnodkar":       "SA Asnodkar",
    "SA Yadav":          "Suryakumar Yadav",
    "SB Bangar":         "Sanjay Bangar",
    "SB Dubey":          "SB Dubey",
    "SB Jakati":         "Shadab Jakati",
    "SB Joshi":          "Sunil Joshi",
    "SB Styris":         "Scott Styris",
    "SB Wagh":           "SB Wagh",
    "SC Ganguly":        "Sourav Ganguly",
    "SC Kuggeleijn":     "SC Kuggeleijn",
    "SD Chitnis":        "SD Chitnis",
    "SD Hope":           "Shai Hope",
    "SD Lad":            "SD Lad",
    "SE Bond":           "Shane Bond",
    "SE Marsh":          "Shaun Marsh",
    "SE Rutherford":     "SE Rutherford",
    "SH Johnson":        "SH Johnson",
    "SJ Srivastava":     "SJ Srivastava",
    "SK Raina":          "Suresh Raina",
    "SK Rasheed":        "SK Rasheed",
    "SK Trivedi":        "SK Trivedi",
    "SK Warne":          "Shane Warne",
    "SL Malinga":        "Lasith Malinga",
    "SM Boland":         "SM Boland",
    "SM Curran":         "Sam Curran",
    "SM Harwood":        "SM Harwood",
    "SM Katich":         "Simon Katich",
    "SM Pollock":        "Shaun Pollock",
    "SMSM Senanayake":   "Sachithra Senanayake",
    "SN Khan":           "SN Khan",
    "SN Thakur":         "Shardul Thakur",
    "SO Hetmyer":        "Shimron Hetmyer",
    "SP Fleming":        "Stephen Fleming",
    "SP Goswami":        "SP Goswami",
    "SP Jackson":        "SP Jackson",
    "SP Narine":         "Sunil Narine",
    "SPD Smith":         "Steve Smith",
    "SR Dubey":          "SR Dubey",
    "SR Tendulkar":      "Sachin Tendulkar",
    "SR Watson":         "Shane Watson",
    "SS Agarwal":        "SS Agarwal",
    "SS Cottrell":       "Sheldon Cottrell",
    "SS Iyer":           "Shreyas Iyer",
    "SS Mishra":         "Amit Mishra",
    "SS Mundhe":         "SS Mundhe",
    "SS Prabhudessai":   "Shashank Singh",
    "SS Sarkar":         "Sudip Sarkar",
    "SS Shaikh":         "SS Shaikh",
    "SS Tiwary":         "Saurabh Tiwary",
    "SSB Magala":        "Sisanda Magala",
    "ST Jayasuriya":     "Sanath Jayasuriya",
    "STR Binny":         "Stuart Binny",
    "SU Parakh":         "SU Parakh",
    "SV Samson":         "Sanju Samson",
    "SW Billings":       "Sam Billings",
    "SW Tait":           "Shaun Tait",
    "SZ Mulani":         "Saurabh Mulani",
    "Sachin Baby":       "Sachin Baby",
    "Sakib Hussain":     "Sakib Hussain",
    "Salman Butt":       "Salman Butt",
    "Sameer Rizvi":      "Sameer Rizvi",
    "Sandeep Sharma":    "Sandeep Sharma",
    "Sanvir Singh":      "Sanvir Singh",
    "Saurav Chauhan":    "Saurav Chauhan",
    "Sediqullah Atal":   "Sediqullah Atal",
    "Shahbaz Ahmed":     "Shahbaz Ahmed",
    "Shahid Afridi":     "Shahid Afridi",
    "Shakib Al Hasan":   "Shakib Al Hasan",
    "Shashank Singh":    "Shashank Singh",
    "Shivam Mavi":       "Shivam Mavi",
    "Shivam Sharma":     "Shivam Sharma",
    "Shivam Singh":      "Shivam Singh",
    "Shivang Kumar":     "Shivang Kumar",
    "Shoaib Ahmed":      "Shoaib Ahmed",
    "Shoaib Akhtar":     "Shoaib Akhtar",
    "Shoaib Malik":      "Shoaib Malik",
    "Shubman Gill":      "Shubman Gill",
    "Sikandar Raza":     "Sikandar Raza",
    "Simarjeet Singh":   "Simarjeet Singh",
    "Sohail Tanvir":     "Sohail Tanvir",
    "Sumit Kumar":       "Sumit Kumar",
    "Sunny Gupta":       "Sunny Gupta",
    "Sunny Singh":       "Sunny Singh",
    "Suryansh Shedge":   "Suryansh Shedge",
    "Suyash Sharma":     "Suyash Sharma",
    "Swapnil Singh":     "Swapnil Singh",

    # ── T ──────────────────────────────────────────────────────────────────
    "T Banton":          "Tom Banton",
    "T Dahiya":          "T Dahiya",
    "T Henderson":       "T Henderson",
    "T Kohler-Cadmore":  "Tom Kohler-Cadmore",
    "T Kohli":           "T Kohli",
    "T Natarajan":       "T Natarajan",
    "T Shamsi":          "Tabraiz Shamsi",
    "T Stubbs":          "Tristan Stubbs",
    "T Taibu":           "Tatenda Taibu",
    "T Thushara":        "T Thushara",
    "T Vijay":           "T Vijay",
    "TA Boult":          "Trent Boult",
    "TD Paine":          "Tim Paine",
    "TG Southee":        "Tim Southee",
    "TH David":          "Tim David",
    "TK Curran":         "Tom Curran",
    "TL Seifert":        "TL Seifert",
    "TL Suman":          "TL Suman",
    "TM Dilshan":        "Tillakaratne Dilshan",
    "TM Head":           "Travis Head",
    "TM Srivastava":     "TM Srivastava",
    "TP Sudhindra":      "TP Sudhindra",
    "TR Birt":           "TR Birt",
    "TS Mills":          "Tymal Mills",
    "TU Deshpande":      "Tushar Deshpande",
    "Tanush Kotian":     "Tanush Kotian",
    "Tejas Baroka":      "Tejas Baroka",
    "Tilak Varma":       "Tilak Varma",

    # ── U ──────────────────────────────────────────────────────────────────
    "U Kaul":            "Udit Kaul",
    "UA Birla":          "UA Birla",
    "UBT Chand":         "Unmukt Chand",
    "UT Khawaja":        "Usman Khawaja",
    "UT Yadav":          "Umesh Yadav",
    "Umar Gul":          "Umar Gul",
    "Umran Malik":       "Umran Malik",
    "Urvil Patel":       "Urvil Patel",

    # ── V ──────────────────────────────────────────────────────────────────
    "V Kaverappa":       "Vijaykumar Vyshak",
    "V Kohli":           "Virat Kohli",
    "V Nigam":           "V Nigam",
    "V Pratap Singh":    "V Pratap Singh",
    "V Puthur":          "V Puthur",
    "V Sehwag":          "Virender Sehwag",
    "V Shankar":         "Vijay Shankar",
    "V Suryavanshi":     "Vaibhav Suryavanshi",
    "V Viyaskanth":      "V Viyaskanth",
    "VG Arora":          "VG Arora",
    "VH Zol":            "VH Zol",
    "VR Aaron":          "Varun Aaron",
    "VR Iyer":           "Venkatesh Iyer",
    "VRV Singh":         "VRV Singh",
    "VS Malik":          "VS Malik",
    "VS Yeligati":       "VS Yeligati",
    "VVS Laxman":        "VVS Laxman",
    "VY Mahesh":         "VY Mahesh",
    "Vijaykumar Vyshak": "Vijaykumar Vyshak",
    "Virat Singh":       "Virat Singh",
    "Vishnu Vinod":      "Vishnu Vinod",
    "Vivrant Sharma":    "Vivrant Sharma",

    # ── W ──────────────────────────────────────────────────────────────────
    "W Jaffer":          "Wasim Jaffer",
    "W O'Rourke":        "Will O'Rourke",
    "WA Mota":           "WA Mota",
    "WD Parnell":        "Wayne Parnell",
    "WG Jacks":          "Will Jacks",
    "WP Saha":           "Wriddhiman Saha",
    "WPUJC Vaas":        "Chaminda Vaas",
    "Washington Sundar": "Washington Sundar",

    # ── X ──────────────────────────────────────────────────────────────────
    "X Thalaivan Sargunam": "X Thalaivan Sargunam",
    "XC Bartlett":       "Xavier Bartlett",

    # ── Y ──────────────────────────────────────────────────────────────────
    "Y Gnaneswara Rao":  "Y Gnaneswara Rao",
    "Y Nagar":           "Y Nagar",
    "Y Prithvi Raj":     "Y Prithvi Raj",
    "Y Venugopal Rao":   "Y Venugopal Rao",
    "YA Abdulla":        "Yusuf Abdulla",
    "YBK Jaiswal":       "Yashasvi Jaiswal",
    "YK Pathan":         "Yusuf Pathan",
    "YS Chahal":         "Yuzvendra Chahal",
    "YV Dhull":          "YV Dhull",
    "YV Takawale":       "YV Takawale",
    "Yash Dayal":        "Yash Dayal",
    "Yash Raj Punja":    "Yash Raj Punja",
    "Yash Thakur":       "Yash Thakur",
    "Yashpal Singh":     "Yashpal Singh",
    "Younis Khan":       "Younis Khan",
    "Yudhvir Singh":     "Yudhvir Singh",
    "Yuvraj Singh":      "Yuvraj Singh",

    # ── Z ──────────────────────────────────────────────────────────────────
    "Z Khan":            "Zaheer Khan",
    "Zeeshan Ansari":    "Zeeshan Ansari",
}


# ---------------------------------------------------------------------------
# Reverse lookup — canonical name → DB shortcode
# Used by PlayerAnalyst, MatchupAnalyst, Compare page
# to convert user-facing full names back to DB format for queries
# ---------------------------------------------------------------------------

CANONICAL_TO_ALIAS = {
    canonical: raw
    for raw, canonical in PLAYER_REGISTRY.items()
    if canonical != raw  # only include entries where a real mapping exists
}